feat: [HL-36] Create logger with default logger🍕
motoon-eg/healthy pull request #36
Opened 2023-05-31 12:15 UTC by djayyab

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-05-31 20:55 UTC, ahmdmhasn requested changes
Files changed should include changes related to the ticket only.

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +}
SHould be added to a separate file

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +struct Logger {
```suggestion
final class Logger {
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    static func logDebug(_ message: String,
```suggestion
    }()
    
    static func logDebug(_ message: String,
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    static func logInfo(_ message: String,
```suggestion
    }
    
    static func logInfo(_ message: String,
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    static func logWarn(_ message: String,
```suggestion
    }
    
    static func logWarn(_ message: String,
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    static func logVerbose(_ message: String,
```suggestion
    }
    
    static func logVerbose(_ message: String,
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    static func logError(_ message: String,
```suggestion
    }
    
    static func logError(_ message: String,
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +class CachLogger: Logging {
```suggestion
final class FileSystemLogger: Logging {
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +class CachLogger: Logging {
Also, please move this to a separate file

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +}
```suggestion
// MARK: String+Helpers
private extension String {
    func appendLineToURL(fileURL: URL) throws {
        let data = self + "\n"
        try data.appendToURL(fileURL: fileURL)
    }
    
    func appendToURL(fileURL: URL) throws {
        if let data = self.data(using: String.Encoding.utf8) {
            if let fileHandle = FileHandle(forWritingAtPath: fileURL.path) {
                defer {
                    fileHandle.closeFile()
                }
                fileHandle.seekToEndOfFile()
                fileHandle.write(data)
            } else {
                try data.write(to: fileURL, options: .atomic)
            }
        }
    }
}
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    //    static let shared = CachLogger()
```suggestion
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +    private func flushLogCache() {
```suggestion
    private let logQueue = DispatchQueue(label: "", qos: .background, attributes: .concurrent)
    
    func log(_ message: String, level: LogLevel, file: StaticString, function: StaticString, line: UInt) {
        let timestamp = DateFormatter.localizedString(from: Date(), dateStyle: .medium, timeStyle: .medium)
        let logMessage = "\(timestamp) - \(level) - \(file) - \(function) - \(line)"
        logCache.append(logMessage)
        logQueue.async {  [weak self] in self?.flushLogCache()}
        print(logMessage)
    }
    
    private func flushLogCache() {
```

2023-05-31 21:03 UTC, ahmdmhasn commented on Healthy/Classes/AppDelegate.swift
> +        Logger.logError("❌")
```suggestion

```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/images/background-splash.imageset/Rectangle 6.pdf
Should be removed

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/images/background-splash.imageset/Contents.json
Should be removed

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/ValidatorProtocol/HealthyValidationRule .swift
Irrelevant changes. Should be reverted.

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/String+Helpers.swift
> +extension String {
This is tightly related to the logger. Let's add them as private extension in the same logger file.

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logging.swift
> +}
```suggestion
import Foundation

/// The Logging protocol defines a standardized way of logging messages in an application or system.
public protocol Logging {
    func log(_ message: String,
             level: LogLevel,
             file: StaticString,
             function: StaticString,
             line: UInt)
}
```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Generated/UIImage.Generated.swift
Changes should be reverted

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/AppDelegate.swift
> +        Logger.logError("❌")
Dead code, should be removed and added to the pull request description or code documentation as an example

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +final class FileSystemLogger: Logging {
```suggestion
import Foundation

final class FileSystemLogger: Logging {
```

Please keep a message after import statement and between methods!

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +            print("Error writing log to file:\(error)")
```suggestion
            assertionFailure("Error writing log to file:\(error)")
```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +    private func flushLogCache() {
```suggestion
    private let logQueue = DispatchQueue(label: "", qos: .background, attributes: .concurrent)
    
    func log(_ message: String,
             level: LogLevel,
             file: StaticString,
             function: StaticString,
             line: UInt) {
        let timestamp = DateFormatter.localizedString(from: Date(),
                                                      dateStyle: .medium,
                                                      timeStyle: .medium)
        let logMessage = "\(timestamp) - \(level) - \(file) - \(function) - \(line)"
        logCache.append(logMessage)
        logQueue.async {  [weak self] in self?.flushLogCache()}
        print(logMessage)
    }
    
    private func flushLogCache() {
```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +    private let logQueue = DispatchQueue(label: "", qos: .background, attributes: .concurrent)
```suggestion
    private let logQueue = DispatchQueue(label: "com.motoon.default-logger", qos: .background, attributes: .concurrent)
```

Dispatch queue label should never be empty.

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/LogLevel.swift
> +public enum LogLevel {
```suggestion
public enum LogLevel {
```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +        return cachLogger
```suggestion
        }
        
        if NSClassFromString("XCTest") != nil {
            // Unit-test
            return NoOpLogger()
        }
        
        return cachLogger
```

2023-06-01 20:30 UTC, ahmdmhasn commented on HealthyTests/HealthyTests.swift
> +        Logger.logWarn("Warning from Unit Test")
```suggestion
```

2023-06-01 20:30 UTC, ahmdmhasn commented on Healthy.xcodeproj/project.pbxproj
> +		B8574F042A2022AA0028FC4B /* HealthyValidator .swift in Sources */ = {isa = PBXBuildFile; fileRef = B8574F032A2022AA0028FC4B /* HealthyValidator .swift */; };
There're alot of irrelevant changes that should be reverted.

2023-06-01 22:25 UTC, djayyab commented on Healthy/Classes/Utilities/ValidatorProtocol/HealthyValidationRule .swift
How can I revert the changes? manually? these changes make conflict with my branch so I add them

2023-06-03 13:14 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/Logger.swift
> +final class Logger {
```suggestion
import Foundation

final class Logger {
```

2023-06-03 13:14 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/LogLevel.swift
> +public enum LogLevel {
```suggestion
import Foundation

public enum LogLevel {
```

2023-06-03 13:14 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +final class FileSystemLogger: Logging {
```suggestion
import Foundation

final class FileSystemLogger: Logging {
```

2023-06-03 13:14 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +    private func flushLogCache() {
```suggestion
    }
    
    private func flushLogCache() {
```

2023-06-03 13:14 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Logger/FileSystemLogger.swift
> +        }
```suggestion
        }
        
```

2023-06-05 19:21 UTC, ahmdmhasn approved these changes

2023-06-05 19:22 UTC, merged