feat: [HL-16] add fonts and provide access for it  🎨
motoon-eg/healthy pull request #39
Opened 2023-06-01 17:57 UTC by abdallah-7698

## What type of PR is this? (check all applicable)

- [ ] 🎨 Style

## Description

## Related Tickets & Documents

## Added tests?

- [ ] 🙅 no, because they aren't needed

## Added to documentation?

- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-06-01 20:19 UTC, ahmdmhasn requested changes
Please drop any commits that aren't relevant to the pull request. 

<img width="869" alt="Screenshot 2023-06-01 at 11 19 30 PM" src="https://github.com/motoon-eg/healthy/assets/45182214/4cff62b7-e79a-47b5-b4fd-b80e9995d0b0">

2023-06-01 22:19 UTC, ahmdmhasn requested changes

2023-06-01 22:19 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
Please avoing naming fonts with modules.

2023-06-01 22:19 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
Same comment as below.

2023-06-01 22:19 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +import UIKit
Please use the same fonts provided in Figma with exactly the same names. 

https://www.figma.com/file/8ilruINbV0EBVQZP2IQnwB/Food-Recipe-App-(Community)?type=design&node-id=5%3A228&t=EkwGw0Pov8Q6NLVO-1

2023-06-03 13:29 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
```suggestion
// MARK: add appFont func

extension UIFont {
    private enum PoppinsWeight {
        case regular
        case bold
    }

    private static func poppins(ofSize size: CGFloat, weight: PoppinsWeight) -> UIFont {
        let fontName: String = {
            switch weight {
            case .regular:
                return "Poppins-Regular"
            case .bold:
                return "Poppins-Bold"
            }
        }()

        guard let font = UIFont(name: fontName, size: size) else {
            assertionFailure("Unable to get a font with name: \(fontName)")
            return UIFont.systemFont(ofSize: size, weight: weight == .regular ? .regular : .bold)
        }
        
        return font
    }
}
```

2023-06-03 13:29 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
I would suggest moving the getter of the font name to ba a computed property

```swift
        let fontName: String = {
            switch weight {
            case .regular:
                return "Poppins-Regular"
            case .bold:
                return "Poppins-Bold"
            }
        }()
```

2023-06-03 13:29 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
Let's not store the fonts in memory, the system do this for us. Instead, please use computed properties.

2023-06-03 13:29 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
Remove **"Text"** keyword, it's redundant.

2023-06-05 19:16 UTC, ahmdmhasn commented
@abdallah-7698 This one as well

2023-06-13 22:29 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UIFont+Style.swift
> +}
```suggestion
import UIKit

// MARK: - Regular Fonts

extension UIFont {
    static var titleRegular: UIFont {
        poppins(ofSize: 50, weight: .regular)
    }
    
    static var headerRegular: UIFont {
        poppins(ofSize: 30, weight: .regular)
    }
    
    static var largeRegular: UIFont {
        poppins(ofSize: 20, weight: .regular)
    }
    
    static var mediumRegular: UIFont {
        poppins(ofSize: 18, weight: .regular)
    }
    
    static var normalRegular: UIFont {
        poppins(ofSize: 16, weight: .regular)
    }
    
    static var smallRegular: UIFont {
        poppins(ofSize: 14, weight: .regular)
    }
    
    static var smallerRegular: UIFont {
        poppins(ofSize: 11, weight: .regular)
    }
}

// MARK: - Bold Fonts

extension UIFont {
    static var titleBold: UIFont {
        poppins(ofSize: 50, weight: .bold)
    }
    
    static var headerBold: UIFont {
        poppins(ofSize: 30, weight: .bold)
    }
    
    static var largeBold: UIFont {
        poppins(ofSize: 20, weight: .bold)
    }
    
    static var mediumBold: UIFont {
        poppins(ofSize: 18, weight: .bold)
    }
    
    static var normalBold: UIFont {
        poppins(ofSize: 16, weight: .bold)
    }
    
    static var smallBold: UIFont {
        poppins(ofSize: 14, weight: .bold)
    }
    
    static var smallerBold: UIFont {
        poppins(ofSize: 11, weight: .bold)
    }
}

// MARK: Poppins UIFont Helpers

private extension UIFont {
    /// Returns a Poppins UIFont instance with the specified Style.
    static func poppins(ofSize size: CGFloat, weight: UIFont.Weight) -> UIFont {
        let fontName = poppinsFontName(forWeight: weight)
        guard let font = UIFont(name: fontName, size: size) else {
            assertionFailure("Unable to get a font with name: \(fontName)")
            return UIFont.systemFont(ofSize: size, weight: weight)
        }

        return font
    }
    
    /// Returns a Poppins UIFont file name for the given weight.
    static func poppinsFontName(forWeight weight: UIFont.Weight) -> String {
        switch weight {
        case .bold:
            return "Poppins-Bold"
        default:
            return "Poppins-Regular"
        }
    }
}
```

WDYT? 😁

2023-06-13 22:29 UTC, ahmdmhasn reviewed
Just a step! 🚀

2023-06-14 00:38 UTC, oradwanomar reviewed
Ahmed did a great review.
After resolve it's conversation tell me to approve
Great in any way Abdalla ❤️👌🏻

2023-06-15 17:48 UTC, ahmdmhasn approved these changes

2023-06-16 07:05 UTC, merged