feat: [HL-30] Sign-In with Facebook✨
motoon-eg/healthy pull request #59
Opened 2023-06-14 13:44 UTC by esraakhaled

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

2023-06-15 15:05 UTC, oradwanomar requested changes

2023-06-15 15:05 UTC, oradwanomar commented on Healthy/Classes/Modules/Login/LoginViewController.swift
> +//            .store(in: &subscriptions)
remove commented code 
OR 
Add your loading indicator view 
Check this link that will help you make a simple, beautiful and reusable indicator view component 
https://youtu.be/iHeeOULNdFA

2023-06-15 15:05 UTC, oradwanomar commented on Healthy/Classes/Modules/Login/LoginViewController.swift
> +//            .store(in: &subscriptions)
Same as above

2023-06-15 15:05 UTC, oradwanomar commented on Healthy/Classes/Modules/Login/LoginViewController.swift
> +//            .store(in: &subscriptions)
same as above

2023-06-15 15:05 UTC, oradwanomar commented on Healthy/Classes/Modules/Login/LoginViewController.swift
> +        print("Logout")
delete any print statement in production

2023-06-15 18:07 UTC, ahmdmhasn commented on Healthy/Classes/AppDelegate.swift
> +    func configureFacebookSignin(application: UIApplication,
```suggestion
    }
    
    func configureFacebookSignin(application: UIApplication,
```

2023-06-15 18:07 UTC, ahmdmhasn commented on Healthy/Classes/AppDelegate.swift
> +            didFinishLaunchingWithOptions: launchOptions)
```suggestion
            didFinishLaunchingWithOptions: launchOptions
        )
```

2023-06-15 18:10 UTC, ahmdmhasn commented on Healthy/Classes/Modules/Login/LoginViewModel.swift
>      var isShowErrorMessagePublisher: AnyPublisher<String, Never> {
```suggestion
    var errorMessagePublisher: AnyPublisher<String, Never> {
```

is does reflect a boolean not a noun. If this is out of the scope, please add todo.

2023-06-15 18:11 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/Login/Mocks/LoginViewModelMock.swift
> +    }
```suggestion
    var isLoadingIndicatorPublisher: AnyPublisher<Bool, Never> {
        Just(false).eraseToAnyPublisher()
    }

    var isShowErrorMessagePublisher: AnyPublisher<String, Never> {
        Just("").eraseToAnyPublisher()
    }

    var isLoginEnabledPublisher: AnyPublisher<Bool, Never> {
        Just(false).eraseToAnyPublisher()
    }

    var isLoginStatusPublisher: AnyPublisher<Bool, Never> {
        Just(false).eraseToAnyPublisher()
    }
```

2023-06-15 18:11 UTC, ahmdmhasn commented on Healthy/Classes/Utilities/Authentication/Login/FacebookAuthenticator.swift
> +class FacebookAuthenticator: NSObject {
You need to conform authenticator and move all the needed logic inside authenticate. Check Google authenticator please.

2023-06-18 18:41 UTC, ahmdmhasn commented
@esraakhaled Please re-request review when the changes are ready.

2023-06-21 15:57 UTC, closed without merging

2023-06-21 15:57 UTC, esraakhaled commented
it reports a conflict when merging develop