Feat/saved recipes table view cell
motoon-eg/healthy pull request #76
Opened 2023-06-21 11:49 UTC by ahmednasr8898

#### Proposed Changes

Describe the changes proposed in this pull request.

1- Make UI for saved recipes table view cell.
2- Make saved recipes table view cell view model.
3- Adding Unit Test.

#### Related Issues

List any related issues or pull requests.

#### Additional Information

Provide any additional information or context that may be relevant.

#### Screenshot

Required for any UI changes

<img width="564" alt="Screenshot 2023-06-21 at 2 45 41 PM" src="https://github.com/motoon-eg/healthy/assets/63086808/6964ac17-57d9-4286-bdf6-9f713a6ac966">

#### Checklist

- [ ] I have tested these changes locally.
- [ ] I have added appropriate documentation or updated existing documentation.
- [ ] I have added appropriate test coverage or updated existing test coverage.
- [ ] I have updated the changelog (if applicable).
- [ ] I have followed the project's code style and formatting guidelines.
- [ ] I have reviewed and adhered to the project's contributing guidelines.

2023-06-21 20:54 UTC, ahmdmhasn reviewed
Great PR, Thanks! 🎉❤️

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/background-food.imageset/heart-healthy-food-1580231690.jpg
[pattern-food.pdf](https://github.com/motoon-eg/healthy/files/11825991/pattern-food.pdf)

Please use this `pattern-food` image as a placeholder.

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/background-gradient.imageset/Contents.json
Please create the gradient in code.

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/icon-stroke.imageset/Union@1x.svg
Please use PDF or SVG.

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/icon-stroke.imageset/Union@1x.svg
Also, I still don't recognize this image 😅

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +        // TODO: Waiting for add style to title label.
Please add the new styles in the same ticket 🙏🏼

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesCellViewModel/SavedRecipesCellViewModelType.swift
> +/// SavedRecipesCellViewModel Input & Output
Not needed.

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesCellViewModel/SavedRecipesCellViewModel.swift
> +import Foundation
No needed

2023-06-21 20:54 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +class SavedRecipesTableViewCell: UITableViewCell {
```suggestion
extension SavedRecipesTableViewCell { 
    struct ViewModel {
        // Here goes your implementation....
    }
}

final class SavedRecipesTableViewCell: UITableViewCell {
```

2023-06-21 20:54 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/SavedRecipes/Cell/TableViewMock.swift
> +final class SavedRecipesTableViewMock: UITableView, UITableViewDelegate, UITableViewDataSource {
```suggestion
We can reuse it 👏🏼

Also, please move it to `HealthyTests/Mocks/UITableViewMock.swift
final class UITableViewMock: UITableView, UITableViewDelegate, UITableViewDataSource {
```

2023-06-21 20:54 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/SavedRecipes/Cell/TableViewMock.swift
> +final class SavedRecipesTableViewMock: UITableView, UITableViewDelegate, UITableViewDataSource {
Also, you can inject the cell type

2023-06-21 20:54 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/SavedRecipes/Cell/TableViewMock.swift
> +    }
```suggestion
```

2023-06-21 20:54 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCellTests.swift
> +    func test_SavedRecipesCellIsFound() {
Please don't fotget given - when - then pattern

2023-06-21 20:54 UTC, ahmdmhasn commented on HealthyTests/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCellTests.swift
> +        mockTableView.register(UINib.init(nibName: "SavedRecipesTableViewCell", bundle: nil),
Please check how we register the collection view cells and implement a similar approach. Feel free to alugn with @abdallah-7698

2023-06-22 08:50 UTC, ahmednasr8898 commented on Healthy/Resources/Assets.xcassets/icon-stroke.imageset/Union@1x.svg
already use it.

2023-06-22 15:35 UTC, esraakhaled approved these changes

2023-06-23 13:09 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +    func configureCell(viewModel: ViewModel) {
```suggestion
    func update(with viewModel: ViewModel) {
```

2023-06-23 17:57 UTC, ahmdmhasn requested changes

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UILabel+Style.swift
> +        case time
Styles should be abstract and should not use any business names.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UILabel+Style.swift
> +            case .splashHeaderLabel, .splashTitle, .splashSubtitle, .savedRecipesTitle, .savedRecipesSubTitle, .time:
```suggestion
            case .splashHeaderLabel, 
                     .splashTitle, 
                     .splashSubtitle, 
                     .savedRecipesTitle, 
                     .savedRecipesSubTitle, 
                     .time:
```

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UILabel+Style.swift
> +    static let savedRecipesTitleLabel = UIFont.systemFont(ofSize: 14, weight: .bold)
Fonts are integrated, please use them.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Classes/Extensions/UITableView+RegisterNib.swift
> +import UIKit
Excellent

2023-06-23 17:57 UTC, ahmdmhasn commented on HealthyTests/Classes/Mocks/UITableViewMock.swift
> +final class UITableViewMock: UITableView, UITableViewDelegate, UITableViewDataSource {
Please use the generic approach we've talked about.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/background-food.imageset/heart-healthy-food-1580231690.jpg
Not updated.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/icon-stroke.imageset/Union@1x.svg
Please use single style.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Resources/Assets.xcassets/icon-stroke.imageset/Union@1x.svg
Use a better name please.

2023-06-23 17:57 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +}
Please move this block to the top of the file.

2023-06-23 17:58 UTC, ahmdmhasn reviewed
Please check the comments and let me know.

2023-06-25 08:35 UTC, ahmednasr8898 commented on Healthy/Resources/Assets.xcassets/background-food.imageset/heart-healthy-food-1580231690.jpg
i added it in cell Nib and when using kingfisher i will add it as placeholder.

2023-06-25 08:41 UTC, ahmednasr8898 commented
@ahmdmhasn Please can you check new changes.

2023-06-27 11:52 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +        // Here goes your implementation....
Please add the needed properties.

2023-06-27 11:55 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +        // Here goes your implementation....
Please don't forget onTap

2023-06-27 11:55 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.swift
> +
```suggestion
    
    // MARK: Properties
    
    private var toggleBookmark: () -> Void = {}
```

2023-06-27 12:05 UTC, ahmdmhasn commented on Healthy/Classes/Modules/SavedRecipes/Cell/SavedRecipesTableViewCell.xib
> +<?xml version="1.0" encoding="UTF-8"?>
```xml
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.XIB" version="3.0" toolsVersion="21507" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES">
    <device id="retina6_12" orientation="portrait" appearance="light"/>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="21505"/>
        <capability name="Named colors" minToolsVersion="9.0"/>
        <capability name="Safe area layout guides" minToolsVersion="9.0"/>
        <capability name="System colors in document resources" minToolsVersion="11.0"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <objects>
        <placeholder placeholderIdentifier="IBFilesOwner" id="-1" userLabel="File's Owner"/>
        <placeholder placeholderIdentifier="IBFirstResponder" id="-2" customClass="UIResponder"/>
        <tableViewCell contentMode="scaleToFill" selectionStyle="default" indentationWidth="10" rowHeight="196" id="KGk-i7-Jjw" customClass="SavedRecipesTableViewCell" customModule="Healthy" customModuleProvider="target">
            <rect key="frame" x="0.0" y="0.0" width="467" height="196"/>
            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>
            <tableViewCellContentView key="contentView" opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" tableViewCell="KGk-i7-Jjw" id="H2p-sc-9uM">
                <rect key="frame" x="0.0" y="0.0" width="467" height="196"/>
                <autoresizingMask key="autoresizingMask"/>
                <subviews>
                    <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFill" horizontalHuggingPriority="251" verticalHuggingPriority="251" translatesAutoresizingMaskIntoConstraints="NO" id="o1X-a1-R6g">
                        <rect key="frame" x="0.0" y="0.0" width="467" height="196"/>
                    </imageView>
                    <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" distribution="equalSpacing" translatesAutoresizingMaskIntoConstraints="NO" id="7rF-fF-ZKs">
                        <rect key="frame" x="8" y="8" width="451" height="180"/>
                        <subviews>
                            <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" distribution="equalCentering" alignment="bottom" spacing="10" translatesAutoresizingMaskIntoConstraints="NO" id="5gZ-Q1-Az5">
                                <rect key="frame" x="0.0" y="0.0" width="451" height="16"/>
                                <subviews>
                                    <view contentMode="scaleToFill" translatesAutoresizingMaskIntoConstraints="NO" id="hk2-NY-RsQ">
                                        <rect key="frame" x="415" y="0.0" width="36" height="16"/>
                                        <subviews>
                                            <stackView opaque="NO" contentMode="scaleToFill" spacing="3.5" translatesAutoresizingMaskIntoConstraints="NO" id="I0J-54-7OW">
                                                <rect key="frame" x="5.9999999999999982" y="4" width="24.333333333333329" height="8"/>
                                                <subviews>
                                                    <view contentMode="scaleToFill" translatesAutoresizingMaskIntoConstraints="NO" id="AdF-ci-9sw">
                                                        <rect key="frame" x="0.0" y="0.0" width="8" height="8"/>
                                                        <color key="backgroundColor" name="rating"/>
                                                        <constraints>
                                                            <constraint firstAttribute="width" constant="8" id="2lS-Va-2pb"/>
                                                            <constraint firstAttribute="height" constant="8" id="8Ca-5s-5zF"/>
                                                        </constraints>
                                                    </view>
                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="0.0" lineBreakMode="tailTruncation" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAutoresizingMaskIntoConstraints="NO" id="Cxl-Ar-yq0">
                                                        <rect key="frame" x="11.666666666666686" y="0.0" width="12.666666666666664" height="8"/>
                                                        <fontDescription key="fontDescription" type="system" pointSize="8"/>
                                                        <nil key="textColor"/>
                                                        <nil key="highlightedColor"/>
                                                    </label>
                                                </subviews>
                                            </stackView>
                                        </subviews>
                                        <color key="backgroundColor" systemColor="systemBackgroundColor"/>
                                        <constraints>
                                            <constraint firstItem="I0J-54-7OW" firstAttribute="centerY" secondItem="hk2-NY-RsQ" secondAttribute="centerY" id="4PE-d0-twI"/>
                                            <constraint firstAttribute="width" constant="36" id="XvX-j0-Fsc"/>
                                            <constraint firstAttribute="height" constant="16" id="gtz-rM-0Vu"/>
                                            <constraint firstItem="I0J-54-7OW" firstAttribute="centerX" secondItem="hk2-NY-RsQ" secondAttribute="centerX" id="zFr-Lv-kqu"/>
                                        </constraints>
                                    </view>
                                </subviews>
                            </stackView>
                            <stackView opaque="NO" contentMode="scaleToFill" alignment="bottom" spacing="17" translatesAutoresizingMaskIntoConstraints="NO" id="bgb-Ts-Q3m">
                                <rect key="frame" x="0.0" y="133.33333333333334" width="451" height="46.666666666666657"/>
                                <subviews>
                                    <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" spacing="6" translatesAutoresizingMaskIntoConstraints="NO" id="lNe-2P-opI">
                                        <rect key="frame" x="0.0" y="0.0" width="334" height="46.666666666666664"/>
                                        <subviews>
                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="title" textAlignment="natural" lineBreakMode="tailTruncation" numberOfLines="2" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAutoresizingMaskIntoConstraints="NO" id="aYS-5J-z3w">
                                                <rect key="frame" x="0.0" y="0.0" width="334" height="20.333333333333332"/>
                                                <fontDescription key="fontDescription" type="system" pointSize="17"/>
                                                <nil key="textColor"/>
                                                <nil key="highlightedColor"/>
                                            </label>
                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="chef name" textAlignment="natural" lineBreakMode="tailTruncation" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAuto [...]

2023-06-27 12:05 UTC, ahmdmhasn approved these changes

2023-06-27 12:54 UTC, ahmdmhasn approved these changes

2023-06-27 12:54 UTC, ahmdmhasn commented
🐑🐑🐑🚀🚀🚀

2023-06-27 12:56 UTC, merged