feat:[H-69]Saved Recipes <> SavedRecipesViewController & SavedRecipesViewModel
motoon-eg/healthy pull request #82
Opened 2023-06-23 21:11 UTC by esraakhaled

#### Proposed Changes

Describe the changes proposed in this pull request.

#### Related Issues

List any related issues or pull requests.

#### Additional Information

Provide any additional information or context that may be relevant.

#### Screenshot

Required for any UI changes
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-24 at 00 03 56](https://github.com/motoon-eg/healthy/assets/45472327/e1776fbf-b19f-4685-94ee-db941a52c4f1)

#### Checklist

- [ ] I have tested these changes locally.
- [ ] I have added appropriate documentation or updated existing documentation.
- [ ] I have added appropriate test coverage or updated existing test coverage.
- [ ] I have updated the changelog (if applicable).
- [ ] I have followed the project's code style and formatting guidelines.
- [ ] I have reviewed and adhered to the project's contributing guidelines.

2023-06-25 20:34 UTC, esraakhaled commented
@ahmdmhasn

2023-06-27 08:13 UTC, abdelhamid-f-nasser requested changes
Well done on adding the tests and mocks for the feature as well as the well written PR description and screenshot  👏 ⭐ 🚀

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Entities/SavedRecipe.swift
> +struct SavedRecipe: Hashable, Equatable {
Quite the well structured and clean model 👍🏼🚀

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Entities/SavedRecipe.swift
> +    let recipeImageUrl: UIImage?
I think we can rename this to `recipeImage` since it's `UIImage` otherwise we need to change the type to String in order to accept String.

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +class MyTableViewCell: UITableViewCell {
You can add marks to better separate the file:
`// MARK: - Properties`

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +    private func setupConstraints() {
You can also add another mark here example: `// MARK: - Private Methods`

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +    private let myImageView = UIImageView()
We can rename this to RecipeImageView for better readability or a better name denoting what this imageView contains.

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +    private let subtitle1Label = UILabel()
We can rename this to `ratingLabel` for better readability

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +    private let subtitle2Label = UILabel()
We can then rename this to `chefNameLabel` for better readability and coherence.

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/ MyTableViewCell.swift
> +    private let subtitle3Label = UILabel()
Lastly, this can be renamed to `cookingTimeInMinutesLabel` or `preparationTimeInMinutesLabel`

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Entities/SavedRecipe.swift
> +    init(title: String?, recipeImageUrl: UIImage?, rating: Int?, chefName: String?, cookingTime: Int?) {
We can add a mark here for initialization: `// MARK: - Initialization`

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/MyTableViewCell.swift
> +        titleLabel.text = viewModel.title!
We can avoid force unwrapping these properties and use if let or guard let for safe property access.

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/MyTableViewCell.swift
> +class MyTableViewCell: UITableViewCell {
We can rename this class to `SavedRecipeTableViewCell`

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/SavedRecipesViewController.swift
>  final class SavedRecipesViewController: UIViewController {
The code is well structured and the marks are on point !! 👍 🎊

2023-06-27 08:13 UTC, abdelhamid-f-nasser commented on Healthy/Classes/Modules/SavedRecipes/SavedRecipesViewController.swift
> +        viewModel.recipesPublisher
We can separate this to a method that sets up bindings like `setupBindings`.

2023-06-28 08:56 UTC, closed without merging